### PR TITLE
Replace master with latest stable version

### PR DESCRIPTION
**Pull request by jw-han**
Latest stable version of ISAACS 1.0 used for user studies.

### CODE REVIEW

**Comment by j-paterson** [comment]
I would recommend maintaining a separate branch for anything specifically related to the state of the platform for the experiment in our paper. It would be best if we make a new branch off of studyinterface which includes all the general improvements and removes study specific aspects, such as recording to log files.

**Review by jeshlee121 — APPROVED** [review]
good stuff

**Review by jeshlee121 — CHANGES_REQUESTED** [review]
didn't see jesse's comment

**Comment by jw-han** [comment]
@j-paterson

**Pull request closed without merging**
